#!/usr/bin/env node
/**
 * Build the SITE_CONTEXT bundle from the site sources so the Worker can hand
 * the model David's actual writing as ground truth (rather than hand-curated
 * facts). Reads about.md, resume.md, and every published _posts/*.md, strips
 * front matter and Liquid templating, and emits worker/src/context.js.
 *
 * Run before `wrangler deploy` (npm scripts wire this up automatically).
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..");
const out = resolve(here, "..", "src", "context.js");

const sources = [
  { path: "about.md", url: "/about/", label: "About page" },
  { path: "resume.md", url: "/resume/", label: "Resume" },
];

const postsDir = join(repoRoot, "_posts");
for (const f of readdirSync(postsDir).sort()) {
  if (!f.endsWith(".md")) continue;
  const m = f.match(/^(\d{4})-(\d{2})-(\d{2})-(.+)\.md$/);
  if (!m) continue;
  const url = `/${m[1]}/${m[2]}/${m[3]}/${m[4]}.html`;
  sources.push({ path: join("_posts", f), url, label: `Post: ${m[4]}` });
}

function stripFrontmatter(text) {
  if (text.startsWith("---")) {
    const end = text.indexOf("\n---", 3);
    if (end !== -1) return text.slice(end + 4).replace(/^\s+/, "");
  }
  return text;
}

function stripLiquid(text) {
  return text
    .replace(/\{%[^%]*%\}/g, "")
    .replace(/\{\{[^}]*\}\}/g, "")
    .replace(/<img[^>]*>/gi, "")
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/\r/g, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

const sections = [];
for (const s of sources) {
  let raw;
  try {
    raw = readFileSync(join(repoRoot, s.path), "utf8");
  } catch (e) {
    console.warn(`skip ${s.path}: ${e.message}`);
    continue;
  }
  const clean = stripLiquid(stripFrontmatter(raw));
  sections.push(`=== ${s.label} (${s.url}) ===\n${clean}`);
}

const bundle = sections.join("\n\n");

const banner = `// Auto-generated by scripts/build-context.mjs — do not edit by hand.\n// Source: about.md, resume.md, _posts/*.md\n`;
const body = `export const SITE_CONTEXT = ${JSON.stringify(bundle)};\n`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, banner + body, "utf8");

const tokens = Math.round(bundle.length / 4);
console.log(`built ${out}`);
console.log(`  ${sources.length} sources, ${bundle.length} chars (~${tokens} tokens)`);
